# Generated by Django 5.1.4 on 2025-01-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('log_level', models.CharField(choices=[('trace', 'Trace'), ('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], max_length=5)),
                ('occurred_on', models.DateTimeField(auto_now_add=True)),
                ('component', models.CharField(choices=[('ui', 'UI'), ('api', 'API')], max_length=3)),
            ],
        ),
    ]
