version: 1
disable_existing_loggers: False

filters:
  health_check_filter:
    (): server.HealthCheckFilter

formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: False
  uvicorn.error:
    level: ERROR
    handlers: [console]
    propagate: False
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: False
  server:
    level: DEBUG
    handlers: [console]
    propagate: False