# Generated by Django 5.1.4 on 2024-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_default_title',
            field=models.BooleanField(default=True),
        ),
    ]
