# Generated by Django 5.1.4 on 2024-12-30 13:40

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatsession_is_default_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='unique_key',
            field=models.UUIDField(default=bot.models.generate_uuid, editable=False, unique=True, verbose_name='Unique key'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
