name: Build and Push mcp-memory

on:
  push:
    branches:
      - main
    paths:
      - 'mcp/memory/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./mcp/memory
        file: ./mcp/memory/Dockerfile
        push: true
        tags: |
          timbuchinger/mcp-memory:latest
          timbuchinger/mcp-memory:${{ github.run_number }}
